import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-900 text-white p-4 flex justify-between">
          <h1 className="text-xl font-bold">Barbearia</h1>
          <nav className="flex gap-4">
            <Link href="/" className="hover:underline">
              Início
            </Link>
            <Link href="/services" className="hover:underline">
              Serviços
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
